### ISSUE TITLE
Reddit not working in chrome browser

### ISSUE THREAD

**Issue by kuranai** [benwinding/newsit#1]
Hi,

i have seen, that the reddit part is not working at the moment for the chrome browser.
When I open the inspector I can see some errors for reddit:

![image](https://user-images.githubusercontent.com/90623/82206207-19365280-9908-11ea-8ffd-b5224a29549d.png)

If someone want's to take a look, here are the given urls from the message:
* [Cross-Origin Read Blocking (CORB)](https://www.chromestatus.com/feature/5629709824032768)
* [Reject insecure SameSite=None cookies](https://www.chromestatus.com/feature/5633521622188032)
* [Cookies default to SameSite=Lax](https://www.chromestatus.com/feature/5088147346030592)

**Comment by benwinding** [comment]
Thanks for reporting the issue @kuranai,

I just assumed that Reddit was blocking CORS requests, but as you mentioned, it seems that the `CORB` is a Chrome specific thing, the reddit endpoint still works in Firefox.

Looks like it's due to the `content-script` making the request to reddit, when it would be better for the `background-script` to make that request ([as detailed in the StackOverflow answer](https://stackoverflow.com/a/56929473/2419584)).

I'll try and implement this and update the extension soon.

Thanks again, let me know if there's any further issues.
Cheers,
Ben
