### ISSUE TITLE
Working for a site with Firefox but not with Chromium

### ISSUE THREAD

**Issue by grahamperrin** [benwinding/newsit#10]
Spun off from https://github.com/benwinding/newsit/issues/9#issuecomment-846526998

`2.0.5` works for https://www.devever.net/~hl/freenode_abuse in Firefox but not in Chromium; nothing appears after a click on **Check Current Page**.

**Comment by benwinding** [comment]
Hi @grahamperrin,
Should be fixed in `2.0.6`, to sum up the fix: there seems to be an issue with using an `<iframe />` element in some cases (which is how the extension is inserted to the page). So instead I've changed it to use the more modern [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM), which is very similar.
Let me know if the issue persists.
Cheers,
Ben
